### PR TITLE
Create project description

### PR DESCRIPTION
**Pull request by alinamarasca**
Please don't hesitate to change it

### CODE REVIEW

**Review by Mika215 — DISMISSED** [review]
This is a nice one so far.So I am approving your request.
Keep going .

**Review by erkamguresen — DISMISSED** [review]
Thank you Alina, good work !

**Comment by erkamguresen** [comment]
@alinamarasca 2 review is reached. But there are some conflicts. Any body (@alinamarasca @Mika215 @sheybusta @mayuri2510 ) want to resolve conflicts and merge the pull request? 
PS. I do not remember where but I have done this last week, so another person can try.

**Review by erkamguresen — APPROVED** [review]
It seems OK!

**Review by mayuri2510 — APPROVED** [review]
good job

**Pull request merged**
