### PR TITLE
updated backlog file

### PR DESCRIPTION
**Pull request by mayuri2510**
please review and merge file to the main branch

### CODE REVIEW

**Review by alinamarasca — CHANGES_REQUESTED** [review]
You've done a lot of work, but I think, it was a bot wrong direction. Maybe check out someone's else backlog like this one https://github.com/rago89/custom-video-player/blob/main/planning/backlog.md There should be literally users stories "As a user I want to easily member website's address" and than line with checkmark.

**Review by erkamguresen — CHANGES_REQUESTED** [review]
Main points are highlighted but not in the correct way. Each point must be describing a user story/experience. Please check the following video from this weeks study list. 
https://www.youtube.com/watch?v=apOvF9NVguA&list=PLBUu5aGDLKnbeEx8U-5r436bw6p9wv1rS&index=2
@alinamarasca @mayuri2510 @Mika215 @sheybusta  for understanding the team work style we use, I find the following video list useful;
https://www.youtube.com/watch?v=Z9QbYZh1YXY&list=PLBUu5aGDLKnbeEx8U-5r436bw6p9wv1rS

This is the second link in the study list.

**Comment by mayuri2510** [comment]
@erkamguresen ok ..i will edit and raise a re pull request .can you please let know where did you find this videos,i could not find it in week 1 incremental and development folder

**Comment by erkamguresen** [comment]
@mayuri2510 hello again.  I am also so confused about where to find where in HYF system.  So I did not understand Wednesday check in issue at first, then some people begin to open it.  Honestly, I copied my issue from @alinamarasca. she seemed reasonably done it correct. After seeing what other people done, some things I read earlier begin to make sense. the link is here:
https://github.com/HackYourFutureBelgium/class-13-14/issues/90

and the place the list is located is 
>https://github.com/HackYourFutureBelgium/incremental-development/blob/master/README.md
Under section
>Suggested Study

I am also constantly get lost in the directories.  If you want, you can just just copy paste the things from me to save time.

**Comment by alinamarasca** [comment]
I've asked on Slack, and because everything was changed, seems it is easier to just close this request. 
But the branch will stay so all the work is intact.

**Pull request closed without merging**
